apiVersion: v1
kind: Service
metadata:
  name: pod-probe-server
  namespace: kube-system
  labels:
    app: pod-probe-server
    component: server
spec:
  type: ClusterIP
  selector:
    app: pod-probe-server
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
