apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8snet-checker.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8snet-checker.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - port: {{ .Values.server.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "k8snet-checker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
