apiVersion: v2
name: k8snet-checker
description: Kubernetes 集群网络连通性检测工具
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - network
  - monitoring
  - connectivity
maintainers:
  - name: sgfoot
    email: freeit@126.com
home: https://github.com/yezihack/k8snet-checker
sources:
  - https://github.com/yezihack/k8snet-checker
